server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: nacos:auth-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
        namespace: public
      config:
        server-addr: 192.168.75.128:8848
        namespace: public
        file-extension: yml

keycloak:
  server-url: http://localhost:8080
  realm: master
  client-id: auth-service
  client-secret: your-client-secret
  token-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token