server:
  port: 28081

spring:
  application:
    name: auth-service
  config:
    import: nacos:auth-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        file-extension: yml

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:}
  realm: ${KEYCLOAK_REALM:master}
  client-id: ${KEYCLOAK_CLIENT_ID:auth-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  token-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
