server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: nacos:gateway-service.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
        namespace: public
      config:
        server-addr: 192.168.75.128:8848
        namespace: public
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2

keycloak:
  server-url: http://localhost:8080
  realm: master