server:
  port: 8888

spring:
  config:
    import: "optional:nacos:gateway-service-dev.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
  application:
    name: gateway-service