server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: nacos:user-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
        namespace: public
      config:
        server-addr: 192.168.75.128:8848
        namespace: public
        file-extension: yml
  datasource:
    url: jdbc:mysql://192.168.75.128:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration