server:
  port: 8083

spring:
  application:
    name: admin-service
  config:
    import: nacos:admin-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.128:8848
        namespace: public
      config:
        server-addr: 192.168.75.128:8848
        namespace: public
        file-extension: yml