server:
  port: 28084

spring:
  application:
    name: device-service
  config:
    import:
      - nacos:shared.yml
      - nacos:device-service.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        file-extension: yml
